Add overflow, transition, and transform properties.
danilobuerger/stylelint-config-concentric pull request #5
Opened 2017-06-17 17:03 UTC by josephdburdick

This PR adds missing properties to the `declaration-block-properties-order` config rule.

2017-06-17 17:25 UTC, danilobuerger commented
Thanks @josephdburdick for the PR. Please take a look at https://github.com/brandon-rhodes/Concentric-CSS/ which is the order I want to reflect here.

2017-06-19 00:06 UTC, josephdburdick commented
Hi @danilobuerger are you saying you want all attributes listed from https://github.com/brandon-rhodes/Concentric-CSS/blob/master/style3.css ?

2017-06-19 05:20 UTC, danilobuerger commented
I just want to keep the order the same. Specifically:
```
  /* transform */
  backface-visibility: ;
  perspective: ;
  perspective-origin: ; 
  transform: ;
  transform-origin: ;
  transform-style: ;

  /* tranistions */
  transition: ;
  transition-delay: ;
  transition-duration: ;
  transition-property: ;
  transition-timing-function: ;
```

2017-06-20 22:45 UTC, josephdburdick commented
Hi @danilobuerger, if I make this change can I include *all* possible CSS attributes from `#Concentric-CSS-Complete` in that list?

2017-06-21 04:13 UTC, danilobuerger commented
Sure, if you want to, go ahead!

2017-06-21 21:18 UTC, josephdburdick commented
@danilobuerger All properties have been applied.

2017-06-24 08:51 UTC, danilobuerger requested changes

2017-06-24 08:51 UTC, danilobuerger commented on index.js
> +  'caption-side',
Duplicate, see next line

2017-06-24 08:51 UTC, danilobuerger commented on index.js
> +  'word-break' ,
Remove whitespace before `,`

2017-06-24 08:51 UTC, danilobuerger commented on index.js
> +  'perspective-origin' ,
Remove whitespace before `,`

2017-06-24 21:15 UTC, josephdburdick commented on index.js
> +  'caption-side',
The `background-repeat` is not being repeated here, it's being removed from line 92 and repositioned to better match the array represented in the repo you linked me to.

2017-06-24 21:34 UTC, josephdburdick commented on index.js
> +  'caption-side',
My mistake, I see the repeated value now.

2017-06-26 17:50 UTC, danilobuerger approved these changes

2017-06-26 17:53 UTC, danilobuerger commented
@josephdburdick Thanks again for the great work, I really appreciate it. Would you mind squashing to one commit & amending, or should I do it for you?

2017-06-28 02:33 UTC, josephdburdick commented
@danilobuerger Squashed down to 1 commit.

2017-06-29 12:53 UTC, merged

2017-06-29 12:54 UTC, danilobuerger commented
Thanks!